# Generated by Django 3.2.2 on 2021-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_website',
            old_name='slug',
            new_name='Slug',
        ),
    ]
