# Generated by Django 3.2.2 on 2021-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0002_rename_slug_blog_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_website',
            name='Slug',
            field=models.SlugField(max_length=200),
        ),
    ]
