# Generated by Django 3.2.2 on 2021-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0003_alter_blog_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_website',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
