# Generated by Django 3.2.2 on 2021-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0004_alter_blog_website_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_website',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
