# Generated by Django 3.2.2 on 2021-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_app', '0005_alter_blog_website_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_website',
            old_name='Slug',
            new_name='slug',
        ),
    ]
